store/conf/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from conf import settings
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView, )

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('social_django.urls', namespace='social')),

    path('api/v1/', include('api_core.api.urls')),
    path('', include('products.urls')),
    path('customer/', include('customers.urls')),
    path('order/', include('orders.urls')),

    # Django urls for reset password
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='customers/password_reset.html'),
         name='password_reset'),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='customers/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='customers/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(template_name='customers/password_reset_complete.html'),
         name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/customers/urls.py
from django.urls import path
from .views import (
    SignUpView, SigninView,
    logout_view, customer_profile_view,
    OrdersView, order_items_view,
    addresses_view, ChangePasswordView,
    DeleteUserAddress,
)

app_name = 'customers'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SigninView.as_view(), name='sign_in'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('logout/', logout_view, name='logout'),
    path('profile/', customer_profile_view, name='profile'),
    path('addresses/', addresses_view, name='addresses'),
    path('delete_address/<int:pk>/',
         DeleteUserAddress.as_view(), name='delete_address'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('order_items/<int:order_id>/', order_items_view, name='order_items'),

]

store/orders/api/urls.py
from django.urls import path
from .views import offer_code_api_view

urlpatterns = [
    path('offer_code/', offer_code_api_view, name='offer_code_api'),
]

store/orders/urls.py
from django.urls import path

from orders.views import basket_view, delete_item_from_basket, checkout

app_name = 'orders'

urlpatterns = [
    path('basket/', basket_view, name='basket'),
    path('basket/delete/', delete_item_from_basket,
         name='delete_item_from_basket'),
    path('checkout/', checkout, name='checkout'),
]

store/products/urls.py
from django.urls import path
from .views import (IndexView, ShopView,
                    ProductDetail, product_by_category,
                    AboutView, ContactView)

app_name = 'products'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('products/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('categories/<str:category>/',
         product_by_category, name='product_by_category'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

store/orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from conf import settings
from customers.models import Address
from products.models import Product
from djmoney.models.fields import MoneyField


class Discount(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                 related_name='discounts')
    code = models.CharField(max_length=50)
    amount = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = _('discounts')
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')

    def __str__(self):
        return f'{self.customer} {self.amount}%'


class OrderItem(models.Model):
    product_name = models.CharField(max_length=150)
    quantity = models.SmallIntegerField()

    class Meta:
        db_table = _('order_item ')
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')

    def __str__(self):
        return f'{self.product_name}'


class Order(models.Model):
    READY_TO_SHIP = 'ready_to_ship'
    SENDING = 'sending'
    SENT = 'sent'
    STATUS = [
        (READY_TO_SHIP, _('ready_to_ship')),
        (SENDING, _('sending')),
        (SENT, _('sent')),
    ]

    customer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='orders')
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    products = models.ManyToManyField(OrderItem)
    status = models.CharField(
        max_length=15,
        choices=STATUS,
        default=READY_TO_SHIP,
    )
    delivery_method = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_price = MoneyField(
        max_digits=10, decimal_places=2, default_currency='USD')
    discount = models.OneToOneField(
        Discount, on_delete=models.RESTRICT, null=True, blank=True)
    total_price_with_discount = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True,
                                           null=True)

    class Meta:
        db_table = _('orders')
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'{self.customer}'

store/orders/api/views.py
from django.utils.timezone import now
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from orders.models import Discount


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def offer_code_api_view(request):
    if request.method == 'POST':
        offer_code = request.POST.get('offerCode')
        customer = request.user
        try:
            discount = Discount.objects.get(code=offer_code)

            if discount.is_active and discount.expire_date > now() and discount.customer == customer:
                content = {'applied': 'Your discount code was applied correctly.',
                           'amount': discount.amount}
                discount.is_active = False
                discount.save()
                return Response(content, status=status.HTTP_200_OK)

            elif not discount.is_active:
                content = {'used': 'Your discount code has been used.'}
                return Response(content, status=status.HTTP_404_NOT_FOUND)

            elif discount.expire_date < now():
                content = {'expired': 'Your discount code has been used.'}
                return Response(content, status=status.HTTP_404_NOT_FOUND)

        except Discount.DoesNotExist:
            content = {'incorrect offer code': 'Your offer code is incorrect.'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)

store/orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render
from customers.models import Address
from orders.models import Discount, Order
from products.models import Product


def basket_view(request):
    """
    Provides the ability to add products to the basket as well as view the basket
    """
    context = dict()
    if request.method == 'GET':

        if request.session.get('basket'):
            basket = request.session.get('basket')
            product_names = basket.keys()
            context['products_in_basket'] = Product.objects.filter(
                name__in=product_names)
            return render(request, 'orders/basket.html', context)
        else:
            # Empty basket
            return render(request, 'orders/basket.html')

    product_name = request.POST.get('product_name')
    product_quantity = request.POST.get('product_quantity')

    if not request.session.get('basket'):
        number_of_products_is_stock = Product.objects.get(
            name=product_name).number_of_product
        if int(product_quantity) > number_of_products_is_stock or int(product_quantity) > 100:
            messages.error(request, 'More than inventory.')
            # Empty basket
            return render(request, 'orders/basket.html')

        # Adding product to the basket for the first time
        request.session['basket'] = {
            product_name: product_quantity
        }
        context['products_in_basket'] = Product.objects.filter(
            name=product_name)
        return render(request, 'orders/basket.html', context)

    else:
        # Update the basket or add new items to the basket
        basket = request.session.get('basket')
        number_of_products_is_stock = Product.objects.get(
            name=product_name).number_of_product

        if int(product_quantity) > number_of_products_is_stock or int(product_quantity) > 100:
            product_names = basket.keys()
            messages.error(request, 'More than inventory.')
            context['products_in_basket'] = Product.objects.filter(
                name__in=product_names)
            return render(request, 'orders/basket.html', context)

        # Add new item to basket
        basket[product_name] = product_quantity
        request.session.modified = True
        product_names = basket.keys()
        messages.success(request, 'Your basket has been updated.')
        context['products_in_basket'] = Product.objects.filter(
            name__in=product_names)
        return render(request, 'orders/basket.html', context)


def delete_item_from_basket(request):
    """
    Takes the product ID and removes it from the basket
    """
    if request.method == 'POST':
        product_name = Product.objects.get(pk=request.POST.get('productId'))
        basket = request.session.get('basket')
        basket.pop(str(product_name))
        request.session.modified = True
        return HttpResponse('Item deleted')


@login_required
def checkout(request):
    if request.method == 'GET':
        context = dict()
        customer = request.user
        addresses = Address.objects.filter(customer=customer)
        basket = request.session.get('basket')
        total_price = sum(
            [Product.objects.get(name=product_name).price * quantity for product_name, quantity in basket.items()])
        context['total_price'] = total_price
        context['addresses'] = addresses
        return render(request, 'orders/checkout.html', context)

    # If the user has an address registered in the database and uses it to pay an order
    if 'address_id' in request.POST:
        basket = request.session.get('basket')
        delivery_method = request.POST.get('delivery_method')
        total_price = sum(
            [Product.objects.get(name=product_name).price * quantity for product_name, quantity in
             basket.items()]).amount

        if delivery_method == 'standard':
            total_price = total_price
        elif delivery_method == 'expedited':
            total_price += 15
        elif delivery_method == 'priority':
            total_price += 30

        customer = request.user
        address = Address.objects.get(id=request.POST.get('address_id'))

        # If user have an offer code
        if request.POST.get('offer_code'):
            discount = Discount.objects.get(
                code=request.POST.get('offer_code'))
            total_price_with_discount = (
                                                total_price * int(discount.amount)) / 100
            total_price_with_discount = total_price - total_price_with_discount
        else:
            discount = None
            total_price_with_discount = total_price

        order = Order(
            customer=customer,
            address=address,
            delivery_method=delivery_method,
            total_price=total_price,
            discount=discount,
            total_price_with_discount=total_price_with_discount
        )
        order.save()

        [order.products.create(product_name=product_name, quantity=quantity) for product_name, quantity in
         basket.items()]

        # Reduce the number of available products in stock
        [Product.objects.filter(name=product_name).update(number_of_product=F('number_of_product') - int(quantity)) for
         product_name, quantity in basket.items()]

        del request.session['basket']
        return render(request, 'orders/checkout_complete.html')

    # If the user has no address registered in the database
    elif 'address' in request.POST:
        basket = request.session.get('basket')
        delivery_method = request.POST.get('delivery_method')
        total_price = sum(
            [Product.objects.get(name=product_name).price * quantity for product_name, quantity in
             basket.items()]).amount

        if delivery_method == 'standard':
            total_price = total_price
        elif delivery_method == 'expedited':
            total_price += 15
        elif delivery_method == 'priority':
            total_price += 30

        customer = request.user

        # Create a new address and use it in the payment
        # Default address type is HOME

        new_address = Address(
            customer=customer,
            address=request.POST.get('address'),
            country=request.POST.get('country'),
            city=request.POST.get('city'),
            state=request.POST.get('state'),
            postcode=request.POST.get('postcode'),

        )
        new_address.save()
        # If user have an offer code
        if request.POST.get('offer_code'):
            discount = Discount.objects.get(
                code=request.POST.get('offer_code'))
            total_price_with_discount = (
                                                total_price * int(discount.amount)) / 100
            total_price_with_discount = total_price - total_price_with_discount
        else:
            discount = None
            total_price_with_discount = total_price

        order = Order(
            customer=customer,
            address=new_address,
            delivery_method=delivery_method,
            total_price=total_price,
            discount=discount,
            total_price_with_discount=total_price_with_discount
        )
        order.save()

        [order.products.create(product_name=product_name, quantity=quantity) for product_name, quantity in
         basket.items()]

        # Reduce the number of available products in stock
        [Product.objects.filter(name=product_name).update(number_of_product=F('number_of_product') - int(quantity)) for
         product_name, quantity in basket.items()]

        del request.session['basket']
        return render(request, 'orders/checkout_complete.html')

store/orders/templates/orders/basket.html
{% extends 'products/base.html' %}
{% load subtotal %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}

    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'products:index' %}">
                Mars
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                    data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between"
                 id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:shop' %}">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'products:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
                    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                            <div class="input-group-text">
                                <i class="fa fa-fw fa-search"></i>
                            </div>
                        </div>
                    </div>

                    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal"
                       data-bs-target="#templatemo_search">
                        <i class="fa fa-fw fa-search text-dark mr-2"></i>
                    </a>

                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'orders:basket' %}">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark" id="basketBadge"></span>
                    </a>

                    <a class="nav-icon position-relative text-decoration-none" href="#">

                        <a href="{% url 'customers:sign_in' %}"><i
                                class="fa fa-fw fa-user text-dark mr-3"></i></a>
                        <span class="position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark"></span>
                    </a>

                </div>
            </div>

        </div>
    </nav>
    <!-- Close Header -->

    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    {#end Modal#}
    {% if user.is_authenticated %}
        {#Start mini nav#}
        <div class="col-xl-12 d-flex justify-content-center">
            <nav class="navbar navbar-expand-lg ">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link profile-link" href="{% url 'customers:orders' %}">Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link profile-link" href="{% url 'customers:addresses' %}">Addresses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link profile-link" href="{% url 'customers:profile' %}">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link profile-link" href="{% url 'customers:change_password' %}">Change
                                    Password</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link profile-link" href="{% url 'customers:logout' %}">Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <hr>
        {#End mini nav#}
    {% endif %}

    {% if messages %}
        <div class="row d-flex justify-content-center">
            <div class="col-6 alert-col">

                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                        <div class="alert alert-danger d-flex justify-content-center" role="alert">
                            <h6>{{ message }}</h6>
                        </div>


                    {% else %}
                        <div class="alert alert-success d-flex justify-content-center" role="alert">
                            <h6>{{ message }}</h6>
                        </div>

                    {% endif %}
                {% endfor %}

            </div>
        </div>

    {% endif %}


    {% if products_in_basket %}
        {#Start basket table#}
        <table class="table table-sm">
            <thead>
            <tr>
                <th scope="col">IMAGE</th>
                <th scope="col">PRODUCT NAME</th>
                <th scope="col">PRICE</th>
                <th scope="col">QUANTITY</th>
                <th scope="col">SUB TOTAL</th>
                <th scope="col">UPDATE / DELETE</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products_in_basket %}

                {% for product_name,quantity in request.session.basket.items %}

                    {% if product.name == product_name %}

                        <tr id="{{ product.id }}">

                            <td><img class="productImage" src="/media/{{ product.image }}"
                                     alt="{{ product.slug }} image"/>
                            </td>

                            <td>{{ product.name }}</td>

                            <td>{{ product.price }}</td>

                            {#Send new quantity and product name for updating#}
                            <form action="{% url 'orders:basket' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" class="product_name" name="product_name"
                                       value="{{ product.name }}">
                                <td>
                                    <input type="number" id="basket" name="product_quantity"
                                           min="1" max="101" value="{{ quantity }}">
                                </td>

                                <td>{% subtotal_calculator quantity product.price %}</td>
                                <td>

                                    {#                                    Update  button#}
                                    <button type="submit" id="updateItemBtn" class="btn btn-success btn-sm">Update
                                    </button>

                                    {#                                    Delete item from basket button#}
                                    <button type="button" id="{{ product.id }}"
                                            class="btn btn-danger btn-sm deleteItemBtn">Delete
                                    </button>

                                </td>
                            </form>

                        </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}

            </tbody>
        </table>

        {#    Checkout button#}

        <div class="row d-flex justify-content-center">
            <div class="col-md-2 d-flex justify-content-center">
                <a href="{% url 'orders:checkout' %}">
                    <button type="button" class="btn btn-success checkOutBtn">CHECK OUT</button>
                </a>
            </div>
        </div>

        {#    End checkout button#}

    {% else %}
        <div class="col-12 d-flex justify-content-center">
            <h3 class="d-flex justify-content-center">
                Your basket is empty &#128513;
            </h3>
        </div>

    {% endif %}
    {#End basket#}



    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Mars shop</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            Iran West azerbaijan
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:+98-910-762-5968">+98 910 762 59 68</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none"
                               href="mailto:info@company.com">saeedahmadi7714@gmail.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    {#                    <h2 class="h2 text-light border-bottom pb-3 border-light">Products</h2>#}
                    {#                    <ul class="list-unstyled text-light footer-link-list">#}
                    {#                        <li><a class="text-decoration-none" href="#">Luxury</a></li>#}
                    {#                        <li><a class="text-decoration-none" href="#">Sport Wear</a></li>#}
                    {#                        <li><a class="text-decoration-none" href="#">Men's Shoes</a></li>#}
                    {#                        <li><a class="text-decoration-none" href="#">Women's Shoes</a></li>#}
                    {#                        <li><a class="text-decoration-none" href="#">Popular Dress</a></li>#}
                    {#                        <li><a class="text-decoration-none" href="#">Gym Accessories</a></li>#}
                    {#                        <li><a class="text-decoration-none" href="#">Sport Shoes</a></li>#}
                    {#                    </ul>#}
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="{% url 'products:index' %}">Home</a></li>
                        <li><a class="text-decoration-none" href="{% url 'products:about' %}">About Us</a></li>
                        <li><a class="text-decoration-none" href="#">Shop Locations</a></li>
                        <li><a class="text-decoration-none" href="#">FAQs</a></li>
                        <li><a class="text-decoration-none" href="{% url 'products:contact' %}">Contact</a></li>
                    </ul>
                </div>

            </div>


            <div class="w-100 bg-black py-3">
                <div class="container">
                    <div class="row pt-2">
                        <div class="col-12">
                            <p class="text-left text-light">
                                Copyright &copy; 2021 Mars shop
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->


{% endblock %}